import type { Metadata } from 'next';
import './globals.css';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import localFont from 'next/font/local';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Toaster } from '@/components/ui/sonner';

const Nacelle = localFont({
  src: '../public/fonts/Nacelle-Black.woff2',
  variable: '--font-Nacelle',
});
const LibreSerif = localFont({
  src: '../public/fonts/LibreBaskerville-Regular.woff2',
  variable: '--font-LibreSerif',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${Nacelle.variable} ${GeistMono.variable} ${GeistSans.variable} ${LibreSerif.variable} no-scrollbar h-screen w-screen bg-background font-sans text-base text-foreground antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          disableTransitionOnChange
          enableSystem
        >
          <main className='flex h-full w-full flex-col justify-between'>
            {children}
          </main>
        </ThemeProvider>

        <Toaster />
      </body>
    </html>
  );
}
